pessoa = {'Nome': 'Profª. Anna', 'Idade': 38, 'Cursos': ['Inglês', 'Português']}
print (type(pessoa))
print (dir(dict))
print (len(pessoa))
print (pessoa)
print (pessoa['Nome'])
print (pessoa['Idade'])
print (pessoa['Cursos'])
print (pessoa['Cursos'][1])
print (pessoa['Cursos'][0])
print (pessoa.keys())
print (pessoa.values())
print (pessoa.items())
print (pessoa.get('Idade'))
print (pessoa.get('tags',[]))
