lista = [1, 5, 'Rebeca', 'Guilherme', 3.1415]
print (lista.index('Guilherme'))
#print (lista.index(42))
print (lista[2])
print (1 in lista)
print ('Rebeca' in lista)
print ('Pedro' not in lista)
print (lista[0])
print (lista[4])
#print (lista[5])
print (lista[-1])
print (lista[-5])