tupla = tuple()
tupla = ()
print (type(tupla))
print (dir(tupla))
help(tuple)
tupla = ('um')
print (type(tupla))
tupla = ('um',)
print (type(tupla))
print (tupla[0])
# as tuplas não podem ser alteradas.
#tupla[0] = 'novo'
cores = ('verde', 'amarelo', 'azul', 'branco')
print (cores[0])
print (cores[-1])
print (cores[1:])
print (cores.index('amarelo'))
print (cores.count('azul'))
print (len(cores))