tupla = tuple()
tupla = ()
print (type(tupla))
#print (dir(tupla))
#print (help(tuple))
# sem a vírgula no final você pode estar criando uma string e não uma tupla.
tupla = ('um')
print (type(tupla))
tupla = ('um',)
print (type(tupla))
print (tupla[0])
print (tupla[0])
# print (tupla[0]) = 'novo'
cores = ('verde', 'amarelo', 'azul', 'braco')
print (cores[0])
print (cores[-1])
print (cores[1:])
print (cores.index('amarelo'))
print (cores.count('azul'))
print (len(cores))
